export const messages = {
  UPDATE_EMPLOYEE_PERSONAL : 'Update employee',
  UPDATE_Client : 'Update client',
  EMPLOYEE_LOGIN: 'Employee login',
  EMPLOYEE_LOGGEDIN: 'Log in successfull',
  LOGIN: 'Login into your account',
  ADMIN_LOGGEDIN: 'Log in successfull',
  MILESTONE_LINK_UPDATE: 'Milestone link updated successfully',
  MILESTONE_LINK_CREATED: 'Milestone link created successfully',
  MILESTONE_LINK_DELETED: 'Milestone link deleted successfully',
  PROJECT_DOCUMENT_SUMMARY: 'Adding project documents',
  PROJECT_DOCUMENT_SAVED: 'Project documents saved successfully',
  PROJECT_DOCUMENT_UPDATED: 'Project documents updated successfully',
  BAD_REQUEST: 'Bad request',
  GET_PROJECT_DOCUMENT_DETAILS: 'Get project documents',
  PROJECT_DOCUMENT_FETCHED: 'Project fetched successfully',
  PROJECT_ASSGINEE_SUMMARY: 'Assigning team to project',
  PROJECT_ASSIGNEE_SAVED: 'Team assigned successfully',
  PROJECT_ASSIGNEE_UPDATED: 'Team updated succussfully',
  PROJECT_ASSIGNEE_FETCHED: 'Team fetched successfully',
  PROJECT_FETCHING_EMPLOYEE: 'Get employee by search',
  PROJECT_EMPLOYEE_FETCHED: 'Employee fetched successfully',
  GET_PROJECT_TEAM: 'Get team members',
  TEAM_FETCHED_SUCCESSFULLY: 'Team members fetched successfully',
  EMPLOYEE_SALARY_SUMMARY: 'Adding employee salary',
  EMPLOYEE_SALARY_SAVED: 'Employee salary saved successfully',
  EMPLOYEE_SALARY_UPDATED: 'Employee salary  updated successfully',
  EMPLOYEE_SALARY_FETCHED: 'Employess salary fetched successfully',
  TASK_SUMMARY: 'Add task',
  TASK_LISTING: 'Get tasks listing',
  TASK_FETCHED: 'Task  fetched successfully',
  TASK_SAVED: 'Task saved successfully',
  TASK_UPDATE: 'Task update successfully',
  GET_TASK_LIST: 'Get all Tasks',
  ADMIN_CREATED: 'Admin created successfully',
  ADMIN_SUMMARY: 'Create admin',
  UPDATE_ADMIN_SUMMARY: 'Update data in  admin',
  UPDATE_ADMIN: 'Admin updated successfully',
  ADD_PROJECT_SUMMARY: 'Create project',
  PROJECT_CREATED: 'Project created successfully',
  GET_PROJECT_LISTING_SUMMARY: 'Get project listing',
  PROJECT_FETCHED: 'Project fetched successfully',
  PROJECT_DETAILS_SUMMARY: 'Project details by id',
  UPDATE_PROJECT_SUMMARY: 'Update project by id',
  PROJECT_UPDATED: 'Project updated successfully',
  ADD_EMPLOYEE_SUMMARY: 'Add employee',
  ADD_CLIENT_SUMMARY: 'Add client',
  EMPLOYEE_CREATED: 'Employee created successfully',
  CLIENT_CREATED: 'Client created successfully',
  GET_EMPLOYEES: 'Get employees',
  GET_Clients: 'Get all clients',
  EMPLOYEE_FETCHED: 'Employees fetched successfully',
  CLIENT_FETCHED: 'Client fetched successfully',
  UPDATE_ADDRESS_EMPLOYEE_SUMMARY: 'Update employees address',
  EMPLOYEE_UPDATED: 'Employees updated successfully',
  Client_UPDATED: 'Client updated successfully',
  EMPLOYEE_JOB_DETAILS_SUMMARY: 'Update employees job details',
  ADD_CREDENTIALS_SUMMARY: 'Add  employees credentials',
  UPDATE_WORK_EXPERIENCE: 'Update employees work experience',
  UPDATE_EDUCATION_EMPLOYEE: 'Update employees education',
  ADD_EDUCATION_EMPLOYEE: 'Add employees education',
  DATA_CRETAED : 'Data created successfully', 
  MILESTONE_ADD_SUMMARY: 'Add project milestone',
  MILESTONE_CREATED: 'Project milestone is created',
  PROJECT_DOCUMENT_UPDATE_SUMMARY: 'Update project documents ',
  MILESTONE_UPDATED: 'Milestone updated successfully',
  GET_MILESTONES: 'Get all milestones',
  MILESTONE_FETCHED: 'Milestone fetched successfully',
  GET_MILESTONE_DETAILS: 'Get milestone details',
  GET_ALL_DROPDOWN: 'Get all drop down valus',
  GET_ALL_DROPDOWN_FETCHED: 'Get all drop down values fetched',
  NOT_FOUND_EMAIL: 'Email not found',
  GET_PROJECT_DETAILS: 'Get project details by id',
  REQUEST_MODULE: ' Change request module',
  REQUEST_MODULE_UPDATE: ' Update request module',
  MODULE_UPDATED: ' Update module successfully',
  REQUEST_MODULE_CHANGED: 'Request module saved successfully',
  REQUEST_MODULE_LISTING: 'Listing request module ',
  REQUEST_MODULE_FETCHED: 'Data fetched successfully',
  REPORTING_CREATE: 'Add Reports by employee',
  REPORT_CREATED: 'Data created successfully',
  LEAVE_MANAGEMENT: 'Leave management ',
  LEAVE_APPLIED: 'Leave applied successfully',
  LEAVE_LISTING: 'Leave data listing',
  LEAVE_FETCHED: 'Leave fetched successfully',
  FORGET_PASSWORD: 'Forget password for given user',
  PASSWORD_UPDATED: 'Password successfully changed',
  PASSWORD_DONT_MATCH: 'Passwords does not match',
  ROLES_PERMISSION_SUMMARY: 'Roles and permissions for employees',
  ROLES_PERMISSION_SAVED: 'Data saved successfully',
  ROLES_PERMISSION_LISTING: 'Roles and permissions for employees',
  ROLES_PERMISSION_FETCHED: 'Roles and permissions for employees fetched',
  MILESTONE_UPDATE_DETAILS : 'Update milestone details',
  DELETE_PROJECT : 'Delete project via admin',
  PROJECT_DELETED : 'Project deleted successfully',
  SOMETHING_WENT_WRONG : 'Internal server error',
  USER_ALREADY_EXISTS : 'User already exists',
  CLIENT_ALREADY_EXISTS : 'Client already exists',
  EMAIL_ALREADY_EXISTS : 'Email already exists',
  EMAIL_NOT_ALLOWED: "Email cannot be updated",
  DELETE_EMPLOYEE : 'Delete employee via admin',
  EMPLOYEE_DELETED : 'Employee deleted successfully',
  EMPLOYEE_REMARKS : 'Remarks for employee',
  REMARKS_SAVED : 'Remarks saved successfully',
  REPORTS_LISTING : 'Listing of reports of projects',
  REPORTS_FETCHED : 'Reports fetched successfully',
  GET_EMPLOYEE_DROPDOWN : 'Get all employee in dropdown',
  GET_PROJECT_DROPDOWN : 'Get all project in dropdown',
  PROJECT_EXISTS : 'Project already exists',
  EMPLOYEE_DETAILS : 'Employee details',
  UNAUTHORIZED : 'Password is incorrect',
  NOT_FOUND : 'Data not found',
  ALREADY_EXIST_EMAIL:'Email already exists',
  RANDOM_EMPLOYEE_ID : 'Random employe id',
  SUCCESS : 'Success',
  DATA_ALREADY_EXISTS : 'Data already exists',
  NAME_ERROR : 'Project name should be atleat 2 character',
  DELETE_MILESTONE : 'Delete milestone and its assignee',
  DELETE_TEAM_MEMBER : 'Delete project team members',
  TEAM_MEMBER_DELETED : 'Team member deleted successfully',
  MILESTONE_DELETED : 'Milestone deleted successfully',
  ASSIGNEE_FIELD : 'Assignee field should not be empty',
  LOGOUT : 'Log out the current user',
  LOGOUT_DONE : 'Log out successfully',
  LOG_ACTIVITY : 'Get log activity',
  LOG_ACTIVITY_FETCHED : 'log activity fetched successfully',
  DELETE_PROJECT_DOCUMENT : 'Delete project document',
  DELETED_DOCUMENT : 'Document deleted successfully',
  MILESTONE_ASSIGNEE : 'Milestone assignee dropdown',
  MILESTONE_ASSIGNEE_FETCHED : 'Assignee fetched successfully',
  DELETE_MODULE : 'Delete module ',
  DELETE_MODULE_LINKS : 'Delete module links',
  MODULE_DELTED : ' Module deleted successfully',
  MODULE_LINKS_DELTED : ' Module links deleted successfully',
  EMPLOYEE_PERMISSIONS : 'Roles and permission of an employee',
  EMPLOYEE_PERMISSION_FETCHED : 'fetched data successfully',
  MODULE_LINKTITLE_UPDATE : 'Update module link title',
  UPDATE_MILESTONE_STATUS : 'Update milestone status',
  UPDATE_MILESTONE_PRIORITY : 'Update milestone priority',
  DELETE_TASKS : ' Delete project tasks',
  TASK_DELETED : 'Task deleted successfully',
  TASK_DETAILS : 'Task details',
  ALL_STATUS_PROJECT : 'Project status count',
  PROJECT_STATUS_COUNT_FETCHED : 'Project status count fetched',
  DATA_FTECHED : 'Data fetched successfully',
  DELETE_CREDENTIALS : 'Delete employee credential',
  CREDENTIAL_DELETED : 'Employee credential deleted successfully',
  DELETE_WORKEXPERIENCE : 'Delete employee work experience',
  WORKEXPERIENCE_DELETED : 'Employee work experience deleted successfully',
  DELETE_EDUCATION : 'Delete employee education',
  EDCUATION_DELETED : 'Employee education deleted successfully',
  GET_REMARKS :'Get remarks for employee',
  DELETE_REMARKS :'Delete remarks for employee',
  REMARKS_DELTED : 'Remarks deleted successfully',
  GET_EMPLOYEE_SALARY :'Employee salary ',
  SALARY_FETCHED : 'Salary fetched successfully',
  ADMIN_SETTINGS : 'Settings for Admin',
  SETTING_SAVED : 'Settings saved successfully',
  CREATE_ADMIN : 'Create admins',
  ADMIN_CRAETED :'Data saved successfully',
  GET_ADMINS : 'Get admins',
  DELETE_ADMIN : 'Delete admins',
  DELETE_CLIENT : 'Delete client',
  ADMIN_DELETED : 'Admin deleted successfully',
  Client_DELETED : 'Client deleted successfully',
  CREATE_CLIENT : 'Create client for projects',
  CLIENT_SAVED : 'Client saved successfully',
};

